[package]
name = "RustPopCat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winreg = "0.6"
resource = "0.5"
winapi = { version = "0.3", features = ["winuser"] }